
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
title: AuthNull - privileged access management with agentless, mfa, 1fa passwordless for all critical infrastructure.
plugins:
  - jekyll-postcss-v2
  - admin

postcss:
  cache: false  

posts:
  permalink: /:blog/:title.html
  permalink: /:blog/:categories/:title/
  permalink: /:categories/:title/

announcements:
  permalink: /:blog/:title.html
  permalink: /:announcement/:categories/:title/

webinar: 
  permalink: /:webinars/:year/:month/:day/:title:output_ext
  permalink: /:webinars/:categories/:title/

casestudy: 
  permalink: /:casestudies/:year/:month/:day/:title:output_ext
  permalink: /:casestudies/:categories/:title/

videos: 
  permalink: /:videos/:year/:month/:day/:title:output_ext
  permalink: /:videos/:categories/:title/

resources: 
  permalink: /:resources/:year/:month/:day/:title:output_ext
  permalink: /:resources/:categories/:title/


architecture: 
  permalink: /:resources/:year/:month/:day/:title:output_ext
  permalink: /:architecture/:categories/:title/




  authors:
  asif:
    name: asif
    display_name: Asif
     
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
    - resources
  layout: archive
  permalinks:
    category: '/category/:name/'
    output: true
permalinks:
    category: '/resource/:name/'
    output: true
collections:
   webinars:
      output: true 
   casestudies:
      output: true
   announcements:
      output: true
   resources:
      output: true
   videos:
      output: true
   authors:
      output: true
   categories:
      output: true
   architecture:
      output: true
      

    

# Pagination 
paginate: 5
paginate_path: ./blog/page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
