
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-postcss-v2
  - admin

postcss:
  cache: false  

posts:
  permalink: /:blog/:title.html
  permalink: /:blog/:categories/:title/

announcements:
  permalink: /:blog/:title.html
  permalink: /:announcement/:categories/:title/

webinar: 
  permalink: /:webinars/:year/:month/:day/:title:output_ext
  permalink: /:webinars/:categories/:title/

casestudy: 
  permalink: /:casestudies/:year/:month/:day/:title:output_ext
  permalink: /:casestudies/:categories/:title/

videos: 
  permalink: /:videos/:year/:month/:day/:title:output_ext
  permalink: /:videos/:categories/:title/

resources: 
  permalink: /:resources/:year/:month/:day/:title:output_ext
  permalink: /:resources/:categories/:title/






  authors:
  asif:
    name: asif
    display_name: Asif
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
    avatar: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=2&w=900&h=900&q=80"
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."
  sal:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    output: true

collections:
   webinars:
      output: true 
   casestudies:
      output: true
   announcements:
      output: true
   resources:
      output: true
   videos:
      output: true
      
 

    

# Pagination 
paginate: 5
paginate_path: ./page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
